# AlertManager configuration for FlowSlide

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@flowslide.com'
  smtp_auth_username: 'alerts@flowslide.com'
  smtp_auth_password: 'your-email-password'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    # Critical alerts go to multiple channels
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    
    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 2h
    
    # Info alerts
    - match:
        severity: info
      receiver: 'info-alerts'
      repeat_interval: 4h

# Inhibition rules
inhibit_rules:
  # Inhibit warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

# Receivers configuration
receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@flowslide.com'
        subject: 'FlowSlide Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@flowslide.com,ops@flowslide.com'
        subject: '🚨 CRITICAL: FlowSlide Alert - {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT FIRED!
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}
    
    # Slack notifications for critical alerts
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts'
        title: '🚨 Critical FlowSlide Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        color: 'danger'
    
    # PagerDuty for critical alerts (optional)
    # pagerduty_configs:
    #   - routing_key: 'YOUR_PAGERDUTY_INTEGRATION_KEY'
    #     description: 'FlowSlide Critical Alert: {{ .GroupLabels.alertname }}'

  - name: 'warning-alerts'
    email_configs:
      - to: 'admin@flowslide.com'
        subject: '⚠️ WARNING: FlowSlide Alert - {{ .GroupLabels.alertname }}'
        body: |
          WARNING ALERT FIRED!
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts'
        title: '⚠️ FlowSlide Warning'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        color: 'warning'

  - name: 'info-alerts'
    email_configs:
      - to: 'admin@flowslide.com'
        subject: 'ℹ️ INFO: FlowSlide Alert - {{ .GroupLabels.alertname }}'
        body: |
          INFO ALERT FIRED!
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt }}
          {{ end }}

# Silence configuration
# silences:
#   - matchers:
#       - name: alertname
#         value: FlowSlideDown
#     startsAt: "2023-01-01T00:00:00Z"
#     endsAt: "2023-01-01T01:00:00Z"
#     createdBy: "admin@flowslide.com"
#     comment: "Planned maintenance"
