name: Delete Workflow Runs

on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:
    inputs:
      runs_to_keep:
        description: '要保留的最新运行条数 (默认: 20)'
        required: false
        default: '20'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs by Count
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          # 只保留这一个条件
          keep_minimum_runs: ${{ github.event.inputs.runs_to_keep || 20 }}
